### ISSUE TITLE
Multiple Results

### ISSUE THREAD

**Issue by stavrosf4** [owenobyrne/node-postcodeanywhere#1]
Dear owenobyrne,

I starting using your package and I noticed that I when I search for a specific postcode, only one result is return. I would like to get back all possible results. Is there any way I can change that?

Thanks,
stavrosf4

**Comment by owenobyrne** [comment]
Howya,
Can you give me an example of a postcode with more than one result? It should return an array of results in JSON. 

Owen

**Comment by stavrosf4** [comment]
Hi again!
For example, when running the code you have as an example (you use SW11 3LJ), I get only one result back (should be more than one).. I would like to have all of the results returned.

Stavros

**Comment by owenobyrne** [comment]
Ah got it - you are looking at the sample on the Postcode Anywhere homepage. That's a different API call to the one I have. I just added the two Capture+ Interactive API calls now. Check the test/test.js script and the API docs on PCA for details.

Let me know if that works or if you need anything else. 

I also pushed v0.0.2 up to NPM so you should be able to upgrade like so:

```
# one-time install the npm update checking tool
npm install -g npm-check-updates
npm-check-updates -u -f postcodeanywhere
```

**Comment by stavrosf4** [comment]
Thank you very much for your help and time
